### ISSUE TITLE
Duration field of Song object is not exposed to Python binding

### ISSUE THREAD

**Issue by ostrosablin** [Polochon-street/bliss-python#1]
While it's possible to get duration through other means, it would be great to be able to just pull it from rust object, since it's gathered anyway, which would save time by avoiding excessive disk accesses just to get song duration.

**Comment by Polochon-street** [comment]
Hi! Just as a heads-up, I've merged your PR, but changed the return type from a float to a timedelta, to match bliss-rs' original return type. Getting the same result as your PR in python should be as easy as getting `song.duration.total_seconds()`
I just published it as v0.1.11, it should be available in pypi. Cheers!

**Comment by ostrosablin** [comment]
Hi! Yes, no problem, I just wasn't sure, how to return a timedelta from Rust. Actually, I wanted to do same at first. I've attempted returning Rust's Duration, but it resulted in pyO3 error during compilation because it was not able to find a matching Python type to convert Duration into, so I've used f64 as a reasonable fallback.

**Comment by Polochon-street** [comment]
it was a bit technical - pyo3's `Duration` is only compatible with [chrono](https://docs.rs/chrono/latest/chrono/)'s `Duration`, so adding that to `Cargo.toml` was needed 😁
